### ISSUE TITLE
imgui can not be drawn when porting to win32

### ISSUE THREAD

**Issue by jrdeng** [jrdeng/imguix#1]
framebuffer size always return (0, 0):

![1](https://cloud.githubusercontent.com/assets/170314/11202748/7f77e7fe-8d26-11e5-8146-bf3d28a319e8.png)

![2](https://cloud.githubusercontent.com/assets/170314/11202753/8760dfd4-8d26-11e5-9b5e-4e98ca32535d.png)

**Comment by jrdeng** [comment]
glfw3.lib has a global named _glfwInintialized....
and it would have two copies in exe and dll...
so exe will always get 0 from glfwGetFramebufferSize()...

![000](https://cloud.githubusercontent.com/assets/170314/11261771/cc1386ee-8eb2-11e5-90ec-0bdacb900995.png)

![001](https://cloud.githubusercontent.com/assets/170314/11261778/d9c6d854-8eb2-11e5-93c2-8a838cfefe21.png)

![002](https://cloud.githubusercontent.com/assets/170314/11261784/e3487414-8eb2-11e5-89e5-ddc831c79528.png)

**Comment by jrdeng** [comment]
after changing glfw3 to dynamic lib(need to modify cocos2d source code), now we can get correct framebuffer size. but still can not draw the imgui : 

![003](https://cloud.githubusercontent.com/assets/170314/11267247/305bf42e-8ee5-11e5-88b3-6882fb87a0b2.png)
![004](https://cloud.githubusercontent.com/assets/170314/11267250/322f0c78-8ee5-11e5-8dae-f11a8b387733.png)

![005](https://cloud.githubusercontent.com/assets/170314/11267473/8b1f5bb6-8ee6-11e5-80f3-a48672d42c9f.png)

and then... comment out   *\*  glUseProgram(0); *\*  in HelloWorld::onDraw()...got this:

![006](https://cloud.githubusercontent.com/assets/170314/11267483/95e0ce2c-8ee6-11e5-9785-9db3d8319d64.png)

**Comment by jrdeng** [comment]
To be continued ?

**Comment by jrdeng** [comment]
ok, let's move the GLViewImpl out of cc2dx. make a copy named IMGUIGLViewImpl in EXE space.

now we are using glfw in EXE space to avoid two copies of glfw3.lib.
and we are gona start at this point:

![imgui widgets not shown](https://cloud.githubusercontent.com/assets/170314/11267473/8b1f5bb6-8ee6-11e5-80f3-a48672d42c9f.png)

**Comment by meiry** [comment]
Thanks for the work on this bug 
Any news with this ?

**Comment by jrdeng** [comment]
Not yet...still working on it.
I'm not very familiar with both cc2dx and imgui. will take more time  :XD

**Comment by meiry** [comment]
Ok thanks , im looking into it also

**Comment by jrdeng** [comment]
@meiry,  jimi has fixed this issue. you can check that if your issue is fixed.
